# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
    branches: main
  workflow_dispatch:

name: render website

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      # Existing jobs
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: pkgdown@2.0.7

      # Custom jobs
      - name: Initialise site
        run: Rscript -e "pkgdown::init_site()"

      - name: Build home
        run: Rscript -e "pkgdown::build_home()"

      - name: Build articles
        run: Rscript -e "pkgdown::build_articles()"

      # Commit
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
